name: GitHub Event Name Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_event_name:
    runs-on: ubuntu-latest

    steps:
      - name: Display Event Name
        run: echo ${{ github.event_name }}
